---
branch: master
collapse_pre_releases: false
stop_at_branch_base: true
sections:
  - [aodh, aodh Chart]
  - [barbican, barbican Chart]
  - [ceilometer, ceilometer Chart]
  - [cinder, cinder Chart]
  - [designate, designate Chart]
  - [glance, glance Chart]
  - [heat, heat Chart]
  - [horizon, horizon Chart]
  - [ironic, ironic Chart]
  - [keystone, keystone Chart]
  - [magnum, magnum Chart]
  - [mistral, mistral Chart]
  - [neutron, neutron Chart]
  - [nova, nova Chart]
  - [octavia, octavia Chart]
  - [placement, placement Chart]
  - [rally, rally Chart]
  - [senlin, senlin Chart]
  - [tempest, tempest Chart]
  - [features, New Features]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes]
  - [api, API Changes]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
template: |
  ---
  # To create a new release note related to a specific chart:
  # reno new <chart_name>
  #
  # To create a new release note for a common change (when multiple charts
  # are changed):
  # reno new common
  <chart_name>:
    - |
      Describe changes here, or remove this section. This paragraph will appear in
      the unnamed section of the <chart_name>/CHANGELOG.md for a given version.
  features:
    - |
      List new features here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "New Features" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  issues:
    - |
      List known issues here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Known Issues" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  upgrade:
    - |
      List upgrade notes here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Upgrade Notes" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  api:
    - |
      List API changes here (e.g. values format), or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "API Changes" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  security:
    - |
      List security issues here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Security Issues" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  fixes:
    - |
      List bug fixes here, or remove this section. If this section is given
      in the releasenotes/notes/<chart_name>-<sha>.yaml it will only appear in the
      "Bug Fixes" section of the <chart_name>/CHANGELOG.md. If this section is
      given in the releasenotes/notes/common-<sha>.yaml it will appear in the
      CHANGELOG.md files of all charts.
  ...
...
